### PR TITLE
Get autokit NPM package under balena scope

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Scoping NPM packages prevents supply chain attacks https://github.blog/2021-02-12-avoiding-npm-substitution-attacks/
Added License
and, updated the lockfile to version 2 that comes with npm v7: https://www.abrahamberg.com/blog/npm-package-json-lock-version-1-or-2/

The last commit is to be merged if everyone has started using node v16 (latest LTS)
If not, I can remove it.

### CODE REVIEW

**Comment by phckopper** [comment]
@vipulgupta2048 Is the Apache license a default balena thing or did you choose it by yourself?

**Comment by vipulgupta2048** [comment]
It has been standard across many repositories

**Comment by phckopper** [comment]
@vipulgupta2048 okay, so please remove the v2 file as we're currently using Node 14, then I'll approve the PR

If we are to make changes to the package name, I believe that the sooner we do it the better

**Comment by rcooke-warwick** [comment]
LGTM - I'll need to update the reference to the package name in this leviathan worker PR @vipulgupta2048 https://github.com/balena-os/leviathan-worker/pull/28

**Comment by vipulgupta2048** [comment]
@phckopper are we still intending to get this through, if yes. I will update my PR and then open a new PR to update leviathan's reference.

**Comment by rcooke-warwick** [comment]
@balena-ci I self-certify!

**Pull request merged**
